### ISSUE TITLE
Municipality code extented by Title of the municipality

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#10]
Would be usefull to add to the municipality code, also municipality title for better and isier navigation and further processing.

**Comment by klimeto** [comment]
@MartinTuchyna cide_establishment table contains attribute city_id which is displayed as municipality id in CIDE. If city_id can be linked to another table which contains the name, we can provide this information. This TBD with project manager and businesses requirements analysists.

**Comment by klimeto** [comment]
Implemented in version 0.1.0 as in following screen:

![image](https://user-images.githubusercontent.com/7523262/48093902-ef7b7600-e210-11e8-89e1-d0c9faf78d52.png)
