### ISSUE TITLE
Automatic update of the amounts of coordinated inspections in the Establishements page

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#15]
When inspection coordinator created the new coordinated inspection (e.g. in case LkQWjnegE3bwZ1p0) after the filling up the form for the "Insert coordinated inspection for LkQWjnegE3bwZ1p0" (attachement 20181023_03) and saving it, he is redirected to the page of establishements, where still remains for this particular establishement an old information (icon with plus sign) instead of the icon with the value 1 which shall be already there indicated the Coordinated inspection was created (attachement 20181023_04). It is probably related to the issue of cashing, but can be confusing for the users and shall automaticaly provide the information about already existing record for the coordinated inspection.
![20181023_03](https://user-images.githubusercontent.com/6195936/47348541-fef7ac80-d6b1-11e8-8c25-73d3ae28009c.PNG)
![20181023_04](https://user-images.githubusercontent.com/6195936/47348543-fef7ac80-d6b1-11e8-98b5-35bdc06c83ef.PNG)

**Comment by klimeto** [comment]
This bug should be fixed in  the last release.
@MartinTuchyna Could you test it and close the issue if fixed?

**Comment by MartinTuchyna** [comment]
Tested, and everything works fine.

**Comment by MartinTuchyna** [comment]
Issue was fixed.
