### ISSUE TITLE
No need to edit date for updated attribute in open issue

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#17]
There is no interrest to keep  the possibility to edit the date of update for the issue by the uset. This date shall be automaticaly  adjusted by the system, when user executes the edits.
![20181023_19](https://user-images.githubusercontent.com/6195936/47366921-ece03300-d6de-11e8-9c11-400cb82bb491.PNG)

**Comment by klimeto** [comment]
@MartinTuchyna disabled editing on Updated field for Specific Inspection.
