### ISSUE TITLE
Coordinated inspoections should have 2 levels

### ISSUE THREAD

**Issue by klimeto** [HRSEVESOSK/cide-ionic-app#18]
It should have option to select either SMS CI or IED CI.

**Comment by klimeto** [comment]
Implemented in last version 0.1.0 with the following values:

- Seveso inspection

- emissions inspection

**Comment by stefanokoki** [comment]
- Seveso

- IED

these are the 2 main types when the coordinator opens a new inspection

**Comment by klimeto** [comment]
Implemented 2 types:
- IED
- Seveso
