### ISSUE TITLE
Update of code list for specific inspection types

### ISSUE THREAD

**Issue by anagolec** [HRSEVESOSK/cide-ionic-app#20]
In the code list for specific inspection types we need to enter new value (SMS_MAPP)

**Comment by klimeto** [comment]
Implemented in last version 0.1.0 with the following values:

- waste inspection

- water inspection

- sanitary inspection

- fire protection inspection

- agricultural inspection

- electric power inspection

- under pressure equipment inspection

- veterinary inspection

- animal inspection

- mine inspection

- work safety inspection

- protection and rescue inspection

- nature inspection

- toxic chemicals management inspection

- safety management

**Comment by stefanokoki** [comment]
this is the final and correct list of inspection types and roles

   cide_admin
   cide_coordinator
   
1.     cide_environmental                    environmental inspection
2.     cide_water                                 water inspection
3.     cide_sanitary                             sanitary inspection
4.     cide_fire                                     fire protection inspection
5.     cide_agricultural                        agricultural inspection
6.     cide_electric                               electric power inspection
7.     cide_pressure                            pressure equipment inspection
8.     cide_veterinary                          veterinary inspection
9.     cide_mine                                   mine inspection
10.   cide_work                                   work safety inspection
11.   cide_protection                          protection and rescue inspection
12.     cide_nature                                nature inspection
13.     cide_toxic                                   toxic chemicals management inspection

**Comment by klimeto** [comment]
@stefanokoki where is the cide_sms-mapp role? Can we make a mapping table between SI types and corresponding CiDE roles to have a clear and referencable source?

**Comment by stefanokoki** [comment]
see the new table containing all types of inspection, ID and relevant institutions, it is the same as before with the addition of the institutions

**Comment by klimeto** [comment]
Final mapping table of CIDE roles, Inspection types and Competent authority is as following:

id | CIDE Role | Inspection   Type | Competent   authority (Organization)
-- | -- | -- | --
1 | ROLE_CIDE_ENV| Environmental   inspection | Ministry of   Environment and Energy
2 | ROLE_CIDE_VOD| Water   inspection | Ministry of   Environment and Energy
3 | ROLE_CIDE_EL| Electroenergy   inspection | Ministry of   Environment and Energy
4 | ROLE_CIDE_ZP| Fire   protection | Ministry of   the Interior
5 | ROLE_CIDE_IZS| Protection   and rescue inspection | National   Protection and Rescue Directorate
6 | ROLE_CIDE_ZNR| Work safety   inspection | Ministry of   Labour
7 | ROLE_CIDE_SAN| Sanitary   inspection | Ministry of   Health
8 | ROLE_CIDE_PRI| Nature   inspection | Ministry of   Environment and Energy
9 | ROLE_CIDE_VET| Veterinary   inspection | Ministry of   Agriculture
10 | ROLE_CIDE_POLJ| Agriculture   inspection | Ministry of   Agriculture
11 | ROLE_CIDE_RUD| Mining   inspection | Ministry of   Economy, Entrepreneurship and Crafts
12 | ROLE_CIDE_OPT| Equipment   under pressure inspection | Ministry of   Economy, Entrepreneurship and Crafts
13 | ROLE_CIDE_IGOK| Toxic   chemicals management inspection | Ministry of Economy,   Entrepreneurship and Crafts

We still need to update the DB table cide_specific_inspection_type to match with this table.
