### ISSUE TITLE
Mapping of inspections to organizations

### ISSUE THREAD

**Issue by anagolec** [HRSEVESOSK/cide-ionic-app#23]
Map the inspections to competent authorities

**Comment by anagolec** [comment]
[Inspections_Organizations.xlsx](https://github.com/HRSEVESOSK/cide-ionic-app/files/2518682/Inspections_Organizations.xlsx)

[PROGRAM KN 2018 KONAČNO_.xlsx](https://github.com/HRSEVESOSK/cide-ionic-app/files/2518686/PROGRAM.KN.2018.KONACNO_.xlsx)

**Comment by klimeto** [comment]
|Inspection Type | Competent authority (Organization)|
| ------------- | ------------- |
|1 | Environmental inspection | Ministry of Environment and Energy|
|2 | Water inspection | Ministry of Environment and Energy|
|3 | Electroenergy inspection | Ministry of Environment and Energy|
|4 | Nature inspection | Ministry of Environment and Energy|
|5 | Sanitary inspection | Ministry of Health|
|6 | Veterinary inspection | Ministry of Agriculture|
|7 | Agriculture inspection | Ministry of Agriculture|
|8 | Mining inspection | Ministry of Economy, Entrepreneurship and Crafts|
|10 | Equipment under pressure inspection | Ministry of Economy, Entrepreneurship and Crafts|
|11 | Dangerous chemicals management inspection | Ministry of Economy, Entrepreneurship and Crafts|
|12 | Work safety inspection | Ministry of Labour|
|13 | Protection and rescue inspection | National Protection and Rescue Directorate|

**Comment by MartinTuchyna** [comment]
En header update of the table PROGRAM.KN.2018.KONACNO_EN-headers
[PROGRAM.KN.2018.KONACNO_EN-headers.xlsx](https://github.com/HRSEVESOSK/cide-ionic-app/files/2519864/PROGRAM.KN.2018.KONACNO_EN-headers.xlsx)

**Comment by anagolec** [comment]
[NEW_Inspections_Organizations.xlsx](https://github.com/HRSEVESOSK/cide-ionic-app/files/2533771/NEW_Inspections_Organizations.xlsx)

I edited the table because there isn't number 9 in the list, fire protection, sorry. And I also reshuffled the table a bit.

**Comment by klimeto** [comment]
@anagolec  please update directly here if you need to add or change the values. 

BTW the Environmental protection is missing in the cide database, table cide_specific_inspection_type as well as in the [Activity 2.3, 2.5 and 3.3 -Business requirements for Coordinated Inspections Data Entry (CIDE) tool ](https://docs.google.com/document/d/1XCC92Gl9K8Z3NWBhG2bj8UrGr-JyGFRjI2kUg9saifM/edit?usp=sharing)

@stefanokoki please ask antonello and paola to integrate this as well as other requests in the documentation as well as database.

id|Inspection Type | Competent authority (Organization)
-- | -- | --
1 | Environmental inspection | Ministry of Environment and Energy
2 | Water inspection | Ministry of Environment and Energy
3 | Electroenergy inspection | Ministry of Environment and Energy
4 | Fire protection | Ministry of the Interior
5 | Protection and rescue inspection | National Protection and Rescue Directorate
6 | Work safety inspection | Ministry of Labour
7 | Sanitary inspection | Ministry of Health
8 | Nature inspection | Ministry of Environment and Energy
9 | Veterinary inspection | Ministry of Agriculture
10 | Agriculture inspection | Ministry of Agriculture
11 | Mining inspection | Ministry of Economy, Entrepreneurship and Crafts
12 | Equipment under pressure inspection | Ministry of Economy, Entrepreneurship and Crafts
13 | Toxic chemicals management inspection | Ministry of Economy, Entrepreneurship and Crafts

**Comment by klimeto** [comment]
@anagolec @stefanokoki is Environmental inspection the same as Waste inspection?

**Comment by anagolec** [comment]
Yes, environmental inspection checks waste and air (emissions)
