### ISSUE TITLE
Insert coordinated inspection for "Name of establishment instead of current ID"

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#24]
When creating the new Coordinated inspection, app shall provide in the top title text contatning the Name of the establishement in order to ensure to support better navigation.

![20181026_01](https://user-images.githubusercontent.com/6195936/47567642-63736f80-d92f-11e8-8186-c469f71711a4.PNG)

**Comment by klimeto** [comment]
@MartinTuchyna 
Fixed in last commit, now displaying the Establishment name in Insert CI modal window opened from getCI modal window.
