### ISSUE TITLE
filling issue reports error 500

### ISSUE THREAD

**Issue by stefanokoki** [HRSEVESOSK/cide-ionic-app#27]
logged as cide_environmental, score filled correctly, after filling issue tried to save but reports 500 internal server error

<img width="1432" alt="schermata 2018-11-26 alle 10 12 25" src="https://user-images.githubusercontent.com/44635661/49004352-65b22f00-f164-11e8-9a04-b89beaf105b7.png">

**Comment by klimeto** [comment]
Try filling also warnings accomplished and indictment.
