### ISSUE TITLE
Update of url for the User manual icon

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#30]
Please update the url for the User manual icon from current both in EN and HR version of landing page:
https://github.com/HRSEVESOSK/cide-ionic-app/wiki/User-manual
into to the
https://github.com/HRSEVESOSK/cide-ionic-app/wiki/02-User-manual
Thanks,
Martin

**Comment by klimeto** [comment]
Updated in current release v 0.2.2

https://pproo.azo.hr/cide/app

@MartinTuchyna Verify and close issue if fixed.

**Comment by MartinTuchyna** [comment]
Tested and fixed.
