### ISSUE TITLE
Wider width of the Score combobox

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#34]
Is it possible to make wider width of the Score combobox in order to allw users to see full lenght of the value text, when selecting? Currently they only see the first 20 characters.

**Comment by klimeto** [comment]
Updated in current release v 0.2.2

https://pproo.azo.hr/cide/app

@MartinTuchyna Verify and close issue if fixed.

**Comment by MartinTuchyna** [comment]
Tested & Fixed.
