### ISSUE TITLE
Strange messages whilst loading the new page

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#35]
Is it possible to eliminate this strange page, showing in background, when new page is loading to the browser saying "CIDE has not opened specific inspection of type ROLE_CIDE_Coordinator" which looks confusing and disturbing. For instance, when user goes from landing page to list of establishements, this page is on the background as on attached snap (20190221_01.png). This behavious happens also in other parts of the app.
![20190221_01](https://user-images.githubusercontent.com/6195936/53163592-b94ee000-35ce-11e9-8d6b-0e27c9274c6e.PNG)

**Comment by klimeto** [comment]
Fixed in current release v 0.2.2

https://pproo.azo.hr/cide/app

@MartinTuchyna Verify and close issue if fixed.

**Comment by MartinTuchyna** [comment]
Tested & Fixed.
