### ISSUE TITLE
Restrict the coordinator from the possibility to delete specific or coordinated inspection, if there is already provided information from Specific coordinator

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#37]
Coordinated inspector shall bot be able to delete either specific or coordinated inspection, if there is already provided input by the Specific inspector.

**Comment by klimeto** [comment]
Role ROLE_CIDE_COORDINATOR since last release v0.2.1 cannot delete any CI, which has already linked SI as well as cannot delete any SI which has linked an instance of score of criteria created by specific inspectors roles.
