### ISSUE TITLE
Small editorial updates of titles for inspections

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#38]
For the coordinated inspection title, please updat the current text:
"Coordinated inspections Rafinerija nafte Rijeka"
to
"Coordinated inspections for establishement Rafinerija nafte Rijeka"

Similarly for the specific inspections, please update the:
"Specific inspection for P8V4y1aKOnaQGw5W"
to
"Specific inspection for Coordinated inspection P8V4y1aKOnaQGw5"

**Comment by klimeto** [comment]
Fixed in current release v 0.2.2

https://pproo.azo.hr/cide/app

@MartinTuchyna Verify and close issue if fixed.

**Comment by MartinTuchyna** [comment]
Tested & Fixed. Perfect. Thanks Tom!
