### ISSUE TITLE
Editorial update of the Report title for Coordinate inspection

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#40]
Current collumn title "Zapisnik! in coordinated inspection table shall be updated to the "Koord. zapisnik".
Similarly in English verion to the "Coord. report". Thanks.

**Comment by klimeto** [comment]
Updated in current release v 0.2.2

https://pproo.azo.hr/cide/app

@MartinTuchyna Verify and close issue if fixed.

**Comment by MartinTuchyna** [comment]
Tested & Fixed.
