### ISSUE TITLE
Missing return arrow from the child elements of the Establishments 

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#6]
There is missing return arrow allowing user to retur from the selected Coordinated inspections (attachement 20181016_03.png), back to the list of establishements as it is available , when user wants to go back from list of esteblishements to the initial page (20181016_04.png)
![20181016_04](https://user-images.githubusercontent.com/6195936/47260708-deb4cb80-d4c0-11e8-80b0-2bd47ab02fa5.PNG)

**Comment by klimeto** [comment]
@MartinTuchyna 

resolved in #4 

If not visible you need to clear the cache.

One thing, I recommend using Firefox to reach better user experience.
