### ISSUE TITLE
Search by Name or OIB

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#8]
In the search area for the establishements it would be useful and for users more helpfull add to surrent text "Search" also "Search by Name or OIB
![20181021_01](https://user-images.githubusercontent.com/6195936/47260938-d78fbc80-d4c4-11e8-85d8-3f958496017b.PNG)
"

**Comment by klimeto** [comment]
Added placeholder: "Search by Name or OIB"
