### ISSUE TITLE
Missing entry page

### ISSUE THREAD

**Issue by MartinTuchyna** [HRSEVESOSK/cide-ionic-app#9]
As indicated on the page 7 of the [CIDE mock-ups presentation](https://drive.google.com/file/d/1XCiBY-TYi1DcCPw3-Ux8r_ACssZnS-0e/view), Its important to provide the landing/intro page with basich information about the application and the underlying project, as well as related contextual information and links.  
1.It migh be possible to do this directly in this url: https://apps.klimeto.com/cide-app/ enterring relevant information and provide an access to the login form either from the same landing url and keep authorisation form in the center of the website, or somewhere else (e.g via micropage),
2. Or via creating the separate websire, before the https://apps.klimeto.com/cide-app/#/login

Relevant textual and graphical content also might be prepared for further finetunning.

**Comment by klimeto** [comment]
@MartinTuchyna if I get the content there is not problem to place in landing home page, which is indeed se to be the one you mentioned first, however if a user is not logged it automatically redirects him to login page. Yet again this tool is meant to be used by expert and authorised users, not for a generic public, thus the information proposed by mockup if any, will be visible only for authorised users. Generic info will be provided by BIFISIC, which is meant to be the main portal to our system.

**Comment by MartinTuchyna** [comment]
Proposal for the page is available on this page:
https://www.draw.io/?state=%7B%22ids%22:%5B%22103gcErT2epjT7jWsaYQ4eAWqqVs_yX-d%22%5D,%22action%22:%22open%22,%22userId%22:%22104472217504663040803%22%7D#G103gcErT2epjT7jWsaYQ4eAWqqVs_yX-d

**Comment by MartinTuchyna** [comment]
There might be provided guidance, from where [CIDE application]([url](https://apps.klimeto.com/cide-app/#/login)) will be linked with BIFISIC [url].(http://pproo.azo.hr/bifisic/map.html#/?_k=kisoye) Just by accident, we have found page on this URL: . http://pproo.azo.hr/cide
Any idea for which purpose serves this url and what is the relationship to the ongoing project?
